# Generated by Django 5.0.8 on 2024-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('nickname', models.CharField(max_length=100, verbose_name='닉네임')),
                ('lat', models.FloatField(default=33.450701, max_length=10, verbose_name='위도')),
                ('lnt', models.FloatField(default=126.570667, max_length=10, verbose_name='경도')),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], default='남성', max_length=50, verbose_name='성별')),
                ('number', models.CharField(max_length=50, verbose_name='연락처')),
                ('birth', models.DateField()),
                ('user_type', models.CharField(choices=[('일반', '일반'), ('기업', '기업')], default='일반', max_length=50, verbose_name='유저타입')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
