# Generated by Django 5.0.8 on 2024-08-07 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='활동지역'),
            preserve_default=False,
        ),
    ]
