# Generated by Django 5.0.8 on 2024-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_img_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='uploads/logo.png', null=True, upload_to='uploads/'),
        ),
    ]
