# Generated by Django 5.0.8 on 2024-08-08 13:52

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리 이름')),
                ('기타', models.PositiveIntegerField(default=0, verbose_name='기타')),
                ('테니스', models.PositiveIntegerField(default=0, verbose_name='테니스')),
                ('헬스', models.PositiveIntegerField(default=0, verbose_name='헬스')),
                ('골프', models.PositiveIntegerField(default=0, verbose_name='골프')),
                ('풋살', models.PositiveIntegerField(default=0, verbose_name='풋살')),
                ('축구', models.PositiveIntegerField(default=0, verbose_name='축구')),
                ('수영', models.PositiveIntegerField(default=0, verbose_name='수영')),
                ('요리', models.PositiveIntegerField(default=0, verbose_name='요리')),
                ('농구', models.PositiveIntegerField(default=0, verbose_name='농구')),
                ('야구', models.PositiveIntegerField(default=0, verbose_name='야구')),
                ('독서', models.PositiveIntegerField(default=0, verbose_name='독서')),
                ('탁구', models.PositiveIntegerField(default=0, verbose_name='탁구')),
                ('양궁', models.PositiveIntegerField(default=0, verbose_name='양궁')),
                ('사격', models.PositiveIntegerField(default=0, verbose_name='사격')),
                ('프라모델', models.PositiveIntegerField(default=0, verbose_name='프라모델')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('기타', '기타'), ('테니스', '테니스'), ('헬스', '헬스'), ('골프', '골프'), ('풋살', '풋살'), ('축구', '축구'), ('수영', '수영'), ('요리', '요리'), ('농구', '농구'), ('야구', '야구'), ('독서', '독서'), ('탁구', '탁구'), ('양궁', '양궁'), ('사격', '사격'), ('프라모델', '프라모델')], default='기타', help_text='다중선택 가능', max_length=47, null=True, verbose_name='취미'),
        ),
        migrations.CreateModel(
            name='UserHobby_click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('hobby_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hobbycategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
