# Generated by Django 5.0.8 on 2024-08-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_hobbycategory_alter_user_hobbies_userhobby_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbycategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='카테고리 이름'),
        ),
        migrations.CreateModel(
            name='TextBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
