# Generated by Django 5.0.8 on 2024-08-08 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_hobbycategory_name_textboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textboard',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
