# Generated by Django 5.0.8 on 2024-08-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_textboard_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='textboard',
            name='lat',
            field=models.FloatField(default=33.450701, max_length=10, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='textboard',
            name='lnt',
            field=models.FloatField(default=126.570667, max_length=10, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='textboard',
            name='content',
            field=models.TextField(),
        ),
    ]
