# Generated by Django 5.0.7 on 2024-08-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_textboard_lat_textboard_lnt_alter_textboard_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
