# Generated by Django 5.0.7 on 2024-08-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_textboard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortMovieBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField(default=33.450701, max_length=10, verbose_name='위도')),
                ('lnt', models.FloatField(default=126.570667, max_length=10, verbose_name='경도')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
