# Generated by Django 5.0.8 on 2024-08-12 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_shortmovieboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dm_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dm_table',
            constraint=models.CheckConstraint(check=models.Q(('sender_id', models.F('receiver_id')), _negated=True), name='no_self_messaging'),
        ),
    ]
