# Generated by Django 5.0.8 on 2024-08-12 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_friendrequst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortmovieboard',
            name='lat',
            field=models.FloatField(default=33.450701, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='shortmovieboard',
            name='lnt',
            field=models.FloatField(default=126.570667, verbose_name='경도'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
