# Generated by Django 5.0.8 on 2024-08-14 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_shortmovieboard_lat_alter_shortmovieboard_lnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhobby_click',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
