# Generated by Django 5.0.8 on 2024-08-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_userhobby_click_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbycategory',
            name='골프',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='기타',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='농구',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='독서',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='사격',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='수영',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='야구',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='양궁',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='요리',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='축구',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='탁구',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='테니스',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='풋살',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='프라모델',
        ),
        migrations.RemoveField(
            model_name='hobbycategory',
            name='헬스',
        ),
    ]
